# Generated by Django 4.1.6 on 2023-02-10 10:03

from django.db import migrations, models
import matinee_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("matinee_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", matinee_auth.models.MatineeUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
