# Generated by Django 4.1.6 on 2023-02-10 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("matinee_auth", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=24, unique=True
            ),
            preserve_default=False,
        ),
    ]
