# Generated by Django 4.1.6 on 2023-02-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matinee_auth", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
