# Generated by Django 4.1.6 on 2023-02-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField(unique=True)),
                ("last_search", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="invitee",
            new_name="invited",
        ),
    ]
