# Generated by Django 4.1.7 on 2023-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_searchterm_rename_invitee_invitation_invited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
